% clearpath -- clears my path to ready for running class data sets

rmpath('c:\mlb\flowrec','c:\mlb\watbal','c:\mlb\stz','c:\mlb\sohel',...
   'c:\mlb\screen','c:\mlb\evol','c:\mlb\convrt','c:\mlb\manip',...
   'c:\mlb\mapdmm','c:\mlb','c:\mlb\rwlook','c:\mlb\public',...
   'c:\mlb\spatrec');