function Y=bootrec1(yhat,E,P,nboot)
% bootrec1:  Generate many reconstruction+noise series by bootstrapping 
% CALL:  Y=bootrec1(yhat,E,P,nboot);
%
% Uses cross-validation errors generated by recflow1.m for the bootstrapping.
%
%
%********************  IN  *************
%
% yhat (m1 x 2)r  reconstructed noiseless series, with year in col 1 (see note)
% E (m2 x nper)r  cross-validation error time series for calibration period
%		for each nof nper models (see notes)
% P (nper x 2)i  start and end year of each reconstruction sub-period
% nboot (1 x 1)i  number of bootstrap series wanted (e.g., 1000)
% 
%
%****************** OUT *********************
%
% No output aruguments, but a user-prompted .mat file with the matrix:
%	
% 	Y (m1 x nboot)r  nboot versions of yhat with added noise

%***************** NOTES *******************
%
% yhat -- Had been generated by a function such as recflow1 such that different
% 	time periods of the reconstruction have different error bars.
%
% E -- these are not the calibration errors, but are the difference
%		between the actual y values and cross-validation estimated times series.
%		Col size of E matches number of reconstruction sub-periods. Row size of
%		E equals size of the full calibration period
%
%----- METHOD
%
% Initialize an m1 x nboot matrix to store recon +noise series
% Prompt for outfile name
% Make pointers
% Loop over sub-period
%		Pull segment of yhat, and appropriate col of E
%		Stack e until row size at least as large as row size of yhat
%		Call bootstrp to get nboot-col matrix of errors
%		Trim the error matrix back to row size of yhat
%		Add yhat to the error matrix --> reconstruction + noise for this subper
%		Store in appropriate rows of the m1-row recon+noise matrix
% End loop over subperiods
% Store Y in .mat file
%
%
%--- FOLLOWUP 
%
% Series of functions to analyze Y. These functions should allow for data
% transform.  An example might be a function to compute the probability that
% any 10-year consecutive period has a flow below some specified leve.  
%
% Another might be the prob that, say, 5 consecutive years of flow below some
% threshold has ever occurred.

