function dayusgs1
% dayusgs1: convert a WWW file of USGS daily flow data to a daily time series matrix and store in a .mat file
% dayusgs1;
% Last revised 2-15-02
%
% Data input function to read a USGS daily-flow file as obtained off the Web and reorganize the data into daily 
% time series matrix.
%
%**** INPUT
%
% No arguments.  User prompted to click on an input USGS data file.
%
%
%*** OUTPUT
%
% No argument.  User prompted to click on an output .mat file to store the daily tsm in.
%
%
%*** REFERENCES -- NONE
%
%*** UW FUNCTIONS CALLED 
%
% day2tsm1 -- utililty function to reformat a block of data
%
% 
%*** NOTES
%
% Assumed format of input file.  The input file, as obtained from the USGS over the Web, must be in the
% following format.  Note that the leading comment symbol (%) is not in the file
%
% #
% # U.S. Geological Survey
% # National Water Information System
% # Retrieved: 2002-02-14 12:28:20 EST
% #
% # This file contains published daily mean streamflow data.
% #
% # Further Descriptions of the dv_cd column can be found at:
% # http://water.usgs.gov/nwis/help?codes_help#dv_cd
% #
% #
% # This information includes the following fields:
% #
% #  agency_cd   Agency Code
% #  site_no     USGS station number
% #  dv_dt       date of daily mean streamflow
% #  dv_va       daily mean streamflow value, in cubic-feet per-second
% #  dv_cd       daily mean streamflow value qualification code
% #
% # Sites in this file include:
% #  USGS 09471000 SAN PEDRO RIVER AT CHARLESTON, ARIZ.
% #
% #
% agency_cd	site_no	dv_dt	dv_va	dv_cd
% 5s	15s	10d	12n	3s
% USGS	09471000	1904-03-29	22	
% USGS	09471000	1904-03-30	17	
% USGS	09471000	1904-03-31	22	
% USGS	09471000	1904-04-01	22


%-- GET THE INPUT AND OUTPUT FILENAMES

[file1,path1]=uigetfile('*.txt','Infile with the USGS-formatted daily data, including the header lines');
pf1=[path1 file1];

[file2,path2]=uiputfile('*.mat','Outfile to store daily time series matrix (tsm) in');
pf2=[path2 file2];


%--- GET THE INPUT DATA

% Read data into cell array of strings, then convert to character
S = char(textread(pf1,'%s','delimiter','\n','whitespace',''));

% Pull the block of lines beginning with U in col 1
c = S(:,1);
L=c=='U';
if ~any(L);
    error(['No lines of ' pf1 ' begin with U in col 1']);
end;
S = S(L,:);
clear L c ;


%--- CONVERT THE DATA

% Call day2tsm1 to convert the matrix of usgs daily data to daily tsm
[X,f,stn] = day2tsm1(S);
% recall that X is the 5 col matrix with cols
% 1=year, 2=month, 3=day of month,4=julian day, 5=data in cfs
% f is a string col-vector with the qualification code
% stn is the USGS station number, as a string



%--- SAVE THE OUTPUT

disp('Writing the output file');
vlist=['File generated by dayusgs1.m on ' date];
vlist=char(vlist,['Input file: ' pf1]);
vlist=char(vlist,['USGS station number = ' stn]);
vlist=char(vlist,'X -- tsm  of year,month,dayofmonth,JulianDay, daily mean streamflow value');
vlist=char(vlist,'f --  string vector of streamflow value qualification code, same row-size as X');

set1 = ' X f stn vlist';
eval(['save ' pf2 set1 ';']);


